### ISSUE TITLE
Remove `Num` instance?

### ISSUE THREAD

**Issue by vrom911** [serokell/o-clock#106]
We already have had the conversation about `Num` instance for `Time` (#14 – issue, #13 – discussion in comments). Time multiplication doesn't make any sense so we agreed on having `error` on illegal actions from `Num` class just to have `fromInteger` that we needed for convenience. And, based on feedback, people don't agree that `error` is acceptable way, so it's better to get rid of any distrustful code we have. I would like to ask you @ChShersh @int-index  if you're also voting for removing these instances?

**Comment by ChShersh** [comment]
I agree with @vrom911 here. Recently I started to value type-safety more than convenience. It's such a pity that we don't have `FromInteger` type class with only single method. But probably after [Compiletime literals](https://github.com/ghc-proposals/ghc-proposals/pull/124) are implemented somehow in GHC, we could make interface of `o-clock` more convenient.

**Comment by int-index** [comment]
I was against this instance in the first place.
