### ISSUE TITLE
support tasty-hspec-1.2

### ISSUE THREAD

**Issue by juhp** [serokell/o-clock#120]
tasty-hspec-1.2 ([changelog](http://hackage.haskell.org/package/tasty-hspec-1.2/changelog)) (Mitchell Rosen <mitchellwrosen@gmail.com> @mitchellwrosen) is out of bounds for:
- [ ] o-clock-1.2.0.1 (^>=1.1.3). Serokell <libraries@serokell.io> @serokell. @serokell. Used by: test-suite

**Comment by gromakovsky** [comment]
I've uploaded [1.2.1 version](https://hackage.haskell.org/package/o-clock-1.2.1) that doesn't depend on `tasty-hspec` anymore.
