### ISSUE TITLE
Introduce constraint alias

### ISSUE THREAD

**Issue by ChShersh** [serokell/o-clock#36]
Often we write something like this in types:

```haskell
foo :: (KnownRat a, KnownRat b, KnownRat (a / b)) => ...
```

I propose to introduce constrain alias for this so we can make types shorter:

```haskell
type a // b = (KnownRat a, KnownRat b, KnownRat (a / b))
```

It allows us to write something like this instead:

```haskell
foo :: a // b => ...
```

Other possible names instead of `//`: `%%` `Div` `%/` `/%` `Divide`

Or we can have both: human-readable name with operator alias.

**Comment by int-index** [comment]
Honestly, if I ever encountered `a // b` in code that I was unfamiliar with, I would never guess that it's related to division, units, or rational numbers. It looks like a C++ comment to me, or set difference.

`KnownDivRat`, perhaps?

**Comment by ChShersh** [comment]
@int-index I agree. `//` name might be far from best... Probably we shouldn't be so fancy here. `KnownDivRat` LGTM.
