### ISSUE TITLE
Ability to create custom list of time units

### ISSUE THREAD

**Issue by vrom911** [serokell/o-clock#46]
In my thoughts, probably it would be helpful to have something to create the list with the given max and min time like `magicSmth Hour Millisecond = '[Hour, Minute, Second, Millisecond]`.

**Comment by ChShersh** [comment]
@vrom911 I think you can try to implement this feature by yourself! You should use type families as always for such tricks. I'm not sure existing examples in `o-clock` can help a lot... But you can at least try to discuss your idea with colleagues and they can guide you through implementation. Unfortunately, I'm not aware of good tutorial on `-XTypeFamilies` extension...

But what also will be cool, is to have type level operator for this. So users can write something like this:

```haskell
seriesF @(Hour .. Millisecond)
```

Not sure that having such operator is possible at all. And not sure about naming (`..` in lists creates in ascending order, while in types it's more convenient to use descending order).
