### ISSUE TITLE
Move to GHC-8.4.1-alpha2

### ISSUE THREAD

**Issue by ChShersh** [serokell/o-clock#58]
See announcement:

* https://mail.haskell.org/pipermail/ghc-devs/2018-January/015323.html

**Comment by ChShersh** [comment]
This should help:

* https://www.reddit.com/r/haskell/comments/7s076d/announce_ghc_841alpha2_available/dt1yvtp/

**Comment by vrom911** [comment]
I updated to `GHC 8.4.1-alpha2` and everything still works fine for me.
```
Build profile: -w ghc-8.4.0.20180118 -O1
```

**Comment by ChShersh** [comment]
@vrom911 So what should I do/change locally to use new ghc?..

**Comment by ChShersh** [comment]
@int-index Should I also change `cabal.project.local`?

**Comment by int-index** [comment]
I don't think so, the path to the compiler should remain the same.

**Comment by ChShersh** [comment]
@vrom911 @int-index Okay, I can confirm that I has latest version of `ghc` and everything still works for me. I'm closing this issue.
