### ISSUE TITLE
`fromReal` function

### ISSUE THREAD

**Issue by vrom911** [serokell/o-clock#70]
Adding `o-clock` to one library I have noticed that there is need to get `TimeStamp` from `Time` for working with `timeDiff` function. It would be nice to have such function in the library.

How I see this function should be:
```haskell
toTimeStamp :: forall unit . KnownRat unit => Time unit -> TimeStamp
toTimeStamp (Time t) = TimeStamp $ toRational t
```

**Comment by ChShersh** [comment]
Such function would be really nice to have! But I think I want more consistency from this function. I would like to have these two values be equal:

```haskell
toTimeStamp (hour 6)
toTimeStamp (minute 360)
```

In other words, this property should hold:

```haskell
toTimeStamp t ≡ toTimeStamp (toUnit @anyTime t)
```

So It looks to me that `toTimeStamp` function should convert `Time` into point in time life starting from zero. It shouldn't matter, how we represent duration: in hours on in picoseconds. The point should be the same for range of same duration.

**Comment by vrom911** [comment]
Closed as it doesn't makes sense
