### ISSUE TITLE
Implement 'fromUnixTime' and probably something else

### ISSUE THREAD

**Issue by ChShersh** [serokell/o-clock#85]
We should have `fromUnixTime :: Real a => a -> Timestamp` function which converts to `Timestamp` from unix time (and probably can be used with `time` library in future).

We probably will have all these functions:

```haskell
fromUnixTime
fromGregorianCalendar
fromJulianCalendar
fromJewishCalendar
```

So I propose to also have:

```haskell
data Calendar = UnixTime | Gregorian | Julian | Jewish

newtype Timestamp (calendar :: Calendar) = ...

fromUnixTime :: Real a => a -> Timestamp 'UnixTime
```

Though, I'm not sure what the are differences between implementations of these functions (except types).

@int-index comment, please.

**Comment by int-index** [comment]
> So I propose to also have

Why would you want the construction method reflected in the types?

**Comment by int-index** [comment]
> Though, I'm not sure what the are differences between implementations of these functions (except types).

Well, take `fromGregorianCalendar` for instance. It would take day, month, and year as input, and produce a timestamp as output. The timestamp is represented as Unix time, so you'd have to perform the conversion, taking leap years into account and so on.

So the implementations will be very different and complex.

**Comment by ChShersh** [comment]
> So the implementations will be very different and complex.

That's not what I want to do...

* https://www.youtube.com/watch?v=-5wpm-gesOY

**Comment by ChShersh** [comment]
> Why would you want the construction method reflected in the types?

If all implementations create UNIX TIME than type parameter is not necessary. But, as you said, this will make implementations much more difficult 🤷‍♂️

**Comment by int-index** [comment]
> That's not what I want to do...

are you writing a library for time or not? 😉 

One of the use cases I have in mind is that after the conversion you can take the diff between these timestamps. So if you need to figure out how 01 Jan 2018 (Gregorian) relates to 22nd of Sh'vat, 5778 (Jewish), you'd convert them both to `Timestamp` and use `timeDiff`.

**Comment by ChShersh** [comment]
> are you writing a library for time or not?

Well, actually not and I don't intend to do it... I wan to have just data types with simple logic. So other libraries have choice:

```haskell
diffTimeToPicoseconds :: DiffTime -> Integer
```

or

```haskell
diffTimeToPicoseconds :: DiffTime -> Time Picosecond
```

Though, as you said, `time` and `clock` libraries will never migrate to `o-clock` and it's usually a rule to build more type-safe API over type-unsafe. And we probably in future can have to package:

1. `o-clock` renamed to `o-clock-core` or `o-clock-data`.
2. And `o-clock` depends on `time`, `clock` and provides more type-safe API. But current I don't want to depend on other libraries and implement more type-safe wrappers.

Let's leave it for future. This issue is only about `fromUnixTime` which behaves almost like constructor module conversion.

**Comment by int-index** [comment]
I think it'd be OK to define only `fromUnixTime` in our lib and then have `o-clock-gregorian`, `o-clock-jewish`, etc., with complex logic and perhaps written by somebody else.
